import random

IMAGES = [
    "AgACAgIAAxkBAAICImpoP92p2UhMoCpfBIICcOjOVdujAAJTHGsbSoNBS0N3C8QRFpMWAQADAgADeQADPQQ",
    "AgACAgIAAxkBAAICJGpoP-GrGI6DQLdrUGDerPZRj9s0AAJUHGsbSoNBS_2Gzzkb0ZZQAQADAgADeQADPQQ",
    "AgACAgIAAxkBAAICJmpoP-Xpykxp7LVd8hCgMbIHc1_gAAJVHGsbSoNBS4jrEzDVWdbsAQADAgADeAADPQQ",
    "AgACAgIAAxkBAAICKGpoP-gXCGSt8IzCeU0l8QHYxm34AAJWHGsbSoNBS2xfayCty6skAQADAgADeQADPQQ",
    "AgACAgIAAxkBAAICKmpoP-tyIpYOCXv-hZKoGPjFXCYlAAJXHGsbSoNBS1IY_JWNd3LMAQADAgADeQADPQQ",
    "AgACAgIAAxkBAAICLGpoP_DGdEaDIBYl5y_FSbPA5ZtxAAJYHGsbSoNBSynnFCwjpfY5AQADAgADeQADPQQ",
]


def get_random_image():
    return random.choice(IMAGES)
